In [2]:
import numpy as np 
import sys

*Basic Numpy Arrays*

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a= np.array([1,2,3,4])

In [5]:
b=np.array([.5,1,1.5,2])

In [6]:
a[1],b[3]

(2, 2.0)

In [7]:
a[0::]

array([1, 2, 3, 4])

In [8]:
b[1:3]

array([1. , 1.5])

In [10]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [12]:
b[-1]

2.0

In [13]:
b[[0,2,-1]]

array([0.5, 1.5, 2. ])

*Array Types*


In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('float64')

In [18]:
np.array([1,2,3,4] , dtype = float)

array([1., 2., 3., 4.])

In [19]:
c= np.array(['a' , 'b' , 'c'])

In [20]:
c.dtype

dtype('<U1')

*Dimensions and shapes*


In [22]:
A = np.array([[1,2,3] , [4,5,6]])

In [23]:
A.shape

(2, 3)

In [25]:
A.ndim

2

In [26]:
A.size

6

In [27]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [28]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [29]:
B.shape

(2, 2, 3)

In [30]:
B.size

12

In [32]:
B.ndim

3

*Indexing and slicing*

In [33]:
A= np.array([[1,2,3] 
             , [4,5,6] 
             ,[7,8,9]])

In [34]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
A[1][0]


4

In [36]:
A[1,0]

4

In [37]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [40]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [41]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
A[2] = 99

In [43]:
A


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

In [44]:
A[1]= np.array([10,10,10])

In [45]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

*Stat*

In [46]:
a = np.array([1,2,3,4])

In [47]:
a.sum()

10

In [48]:
a.mean()

2.5

In [50]:
a.std()

1.118033988749895

In [51]:
a.var()

1.25

In [52]:
A= np.array([[1,2,3] 
             , [4,5,6] 
             ,[7,8,9]])

In [53]:
A.sum()

45

In [54]:
A.mean()

5.0

In [55]:
A.std()

2.581988897471611

In [59]:
A.sum(axis =0)

array([12, 15, 18])

In [60]:
A.mean(axis =1)

array([2., 5., 8.])